### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-payment#102]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [x] account_check_printing_report_base - By @smangukiya - #147
- [x] account_due_list - By @eLBati  - #129 
- [x] account_due_list_payment_mode - ~~By @vonpupp - #130~~ By @Roodin - #141 
- [x] ~~account_payment_order_to_voucher~~ - Voucher not present since v9
- [x] account_payment_return - By @chienandalu - #152
- [x] account_payment_return_import - By @chienandalu - #153 
- [x] account_payment_return_import_sepa_pain - By @chienandalu - #154 
- [x] ~~account_payment_term_multi_day~ - Removed as merged with OCA/account-invoicing/account_payment_term_extension
- [x] ~~account_vat_on_payment~~ - Cash basis already present in odoo core
- [x] ~~account_voucher_cash_basis~~ - Voucher not present since v9
- [x] ~~account_voucher_display_writeoff~~ - Voucher not present since v9
- [x] ~~account_voucher_supplier_invoice_number~~ - Voucher not present since v9
- [x] ~~account_voucher_tax_filter~~ - Voucher not present since v9

**Comment by scigghia** [comment]
Hi Pedro, i've done a mistake, so please consider this PR https://github.com/OCA/account-payment/pull/106
thanks

**Comment by pedrobaeza** [comment]
OK

**Comment by pedrobaeza** [comment]
@eLBati is account_vat_on_payment still needed on v9?

**Comment by eLBati** [comment]
@pedrobaeza it is not needed as is. I still have to analyze if standard module covers every need. I strike through ```account_vat_on_payment```

**Comment by pedrobaeza** [comment]
OK, when you are sure about it, please make the PR removing the module or keeping the parts you need, maybe with a module renaming.

**Comment by bistaray** [comment]
https://apps.odoo.com/apps/modules/9.0/account_payment_show_invoice/ works fine on v10 with no changes.
