### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-payment#161]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] account_check_printing_report_base - By @etobella - #167 
- [x] account_check_printing_report_dlt103 - By @hveficent - #186 
- [x] account_due_list - By @ozono - #170 
- [x] account_due_list_aging_comments - By @mreficent - #197
- [x] account_due_list_days_overdue - By @mreficent - #198 
- [x] account_due_list_payment_mode - By @cubells - #175 
- [x] account_partner_reconcile - ~~By @jaumeplanas - #181~~ By @jbeficent - #187 
- [x] account_payment_batch_process - started by @faryrosa in #190 - WIP by @murtuzasaleh in #255 
- [x] account_payment_credit_card - By @ursais - #195
- [x] account_payment_return - By @luismontalba - #176 
- [x] account_payment_return_import - By @luismontalba - #178 
- [x] account_payment_return_import_sepa_pain - By @luismontalba - #179 
- [x] account_payment_show_invoice to the list - By @mreficent - #199
- [x] partner_aging - By @murtuzasaleh - #260

**Comment by jaumeplanas** [comment]
account_partner_reconcile @jaumeplanas #180

**Comment by jaumeplanas** [comment]
account_partner_reconcile @jaumeplanas #181

**Comment by faryrosa** [comment]
good morning

I have a migration proposal to odoo 11 from account_payment_batch_process that I would like you to please review. I have the branch coming from a fork of account-payment. What would be the procedure?

**Comment by pedrobaeza** [comment]
See https://odoo-community.org/page/code

**Comment by emagdalenaC2i** [comment]
Add the PR number #195 to account_payment_credit_card by @ursais 
account_due_list_aging_comments is already merged - By @mreficent - #197
account_due_list_days_overdue is already merged - By @mreficent - #198 
Please add account_payment_show_invoice to the list. It is already merged - By @mreficent - #199 
Also I did'nt find the PR for partner_aging by @smangukiya or any comment about this migration
