### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-payment#49]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [x] account_due_list - By @jbeficent - #122 
- [x] account_due_list_payment_mode - By @sergio-teruel - #118 
- [x] ~~account_payment_order_to_voucher~~ - Voucher not present in v9
- [x] account_payment_return - By @carlosdauden - #112 
- [x] account_payment_return_import - By @carlosdauden - #116
- [x] account_payment_return_import_sepa_pain - By @carlosdauden - #117 
- [x] account_payment_term_multi_day > Make migration scripts to account_payment_term_extension
- [x] ~~account_vat_on_payment~~ Not needed anymore
- [x] ~~account_voucher_cash_basis~~ - Voucher not present in v9
- [x] ~~account_voucher_display_writeoff~~ - Voucher not present in v9
- [x] ~~account_voucher_supplier_invoice_number~~ - Voucher not present in v9
- [x] ~~account_voucher_tax_filter~~ - Voucher not present in v9

**Comment by damdam-s** [comment]
`account_payment_term_multi_day` migration done in https://github.com/OCA/account-invoicing/pull/141

**Comment by damdam-s** [comment]
@pedrobaeza just to be clear, it's my colleague @jcoux who did the migration. Many thanks to him.
Can you change credit in checkboxes comment please ?

**Comment by pedrobaeza** [comment]
Ah, OK, no problem

**Comment by mtbochaca** [comment]
The translation is not in Transifex. I can not translate it. Thanks.

**Comment by pedrobaeza** [comment]
I have added them. It will be available very soon.
