### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-payment#546]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] account_cash_invoice - By @carlos-lopez-tecnativa - #743
- [x] account_check_printing_report_base - By @hildickethan-S73 - #725
- [x] account_due_list - By @ramiadavid - #550
- [x] account_due_list_aging_comment - By @RodrigoBM - #633
- [x] account_due_list_payment_mode - By @Yadier-Tecnativa - #619
- [x] account_payment_batch_process_discount - By @PauBForgeFlow - #697
- [x] account_payment_credit_card - By @carlos-lopez-tecnativa - #751
- [x] account_payment_line_import - By @JasminSForgeFlow - #678
- [x] account_payment_promissory_note - By @oihane - #612
- [x] account_payment_return - By @Yadier-Tecnativa - #639
- [x] account_payment_return_import - By @Yadier-Tecnativa - #651
- [x] account_payment_return_import_iso20022 - By @heliaktiv - #622
- [x] account_payment_term_extension - By @anothingguy - #580
- [ ] account_payment_term_partner_holiday - By @PabloCatalinaCastello - #744
- [ ] account_payment_widget_amount
- [x] partner_aging - By @cormaza - #733

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by ramiadavid** [comment]
Hi @sbidoul 
Im working in `account_due_list` #550

**Comment by anothingguy** [comment]
I'm working on `account_payment_term_extension` https://github.com/OCA/account-payment/pull/580

**Comment by nguyenhk99** [comment]
`account_financial_discount`: No need to migrate. Odoo V16 did.

**Comment by EstebanBlanc** [comment]
Hi,
account_due_list_payment_mode is missing

**Comment by dsolanki-initos** [comment]
Migrating account_payment_widget_amount https://github.com/OCA/account-payment/pull/632

**Comment by Gelo-fl** [comment]
> Migrating account_payment_widget_amount

Hi @dsolanki-initos Can you add the PR of the migration?

**Comment by dsolanki-initos** [comment]
> > Migrating account_payment_widget_amount
> 
> Hi @dsolanki-initos Can you add the PR of the migration?

Hi, @Gelo-fl, I've Added.

**Comment by Gelo-fl** [comment]
> > > Migrating account_payment_widget_amount
> > 
> > 
> > Hi @dsolanki-initos Can you add the PR of the migration?
> 
> Hi, @Gelo-fl, I've Added.

Thanks :)

**Comment by RodrigoBM** [comment]
Migrating account_due_list_aging_comment https://github.com/OCA/account-payment/pull/633

**Comment by metaminux** [comment]
[**account_payment_batch_process**](https://github.com/OCA/account-payment/tree/15.0/account_payment_batch_process) is missing. Can someone add it to the list ?

**Comment by noharr** [comment]
I had already worked on the migration of this module [account_payment_batch_process] #689
